name: kmutt_news
description: A new Flutter project.

version: 1.0.0+1

environment: 
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dropdownfield: ^1.0.3
  image_picker: ^0.6.7+8
  image: ^2.1.4
  google_fonts: ^1.1.0
  flutter_svg: ^0.19.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0

  cloud_firestore: ^0.14.0
  firebase_database: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - image/addImage.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
